### PR TITLE
🎨 mobile styles

### PR DESCRIPTION
**Pull request by littlemooon**
Fixed in mobile layout:
- width of provider list was not contained in widget
- payment buttons were overflowing width, they are now in flex column

Script:
- added dev script for local yarn linked development
- updated webpack output file to be `widget.js` at all times

screen shot 2018-02-06 at 15 58 23

screen shot 2018-02-06 at 15 55 48

### CODE REVIEW

**Comment by ziggamon** [comment]
Fixes look good. 

Seems based on the last screenshot there is an unrelated bug, displaying a faux bitcoin address to the user, that should not happen. Can you reliably reproduce with an empty account?

**Comment by littlemooon** [comment]
@ziggamon the faux bitcoin address is only shown in local development. i cant reproduce in production

**Comment by ziggamon** [comment]
Ok, that's good. And it's not following along in the app builds for production?

**Comment by littlemooon** [comment]
nope, ive just changed styles

**Comment by ziggamon** [comment]
Just double checking :)

**Pull request merged**
